function census = ImportFindDonor(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CENSUS = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  CENSUS = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  census = importfile("D:\ML\courses\MachineLearningWithTF\codes\projects\p1_charityml\census.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Dec-2020 16:55:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 15);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["age", "workclass", "education_level", "educationnum", "maritalstatus", "occupation", "relationship", "race", "sex", "capitalgain", "capitalloss", "hoursperweek", "nativecountry", "income", "income_b"];
opts.VariableTypes = ["double", "categorical", "categorical", "double", "categorical", "categorical", "categorical", "categorical", "categorical", "double", "double", "double", "categorical", "double", "double"];
opts = setvaropts(opts, 14, "TrimNonNumeric", true);
opts = setvaropts(opts, 14, "ThousandsSeparator", ",");
opts = setvaropts(opts, [2, 3, 5, 6, 7, 8, 9, 13], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
census = readtable(filename, opts);

end