function testcensus = ImportFindDonorTest(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TESTCENSUS = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  TESTCENSUS = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  testcensus = importfile("D:\ML\courses\MachineLearningWithTF\codes\projects\p1_charityml\test_census.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Dec-2020 17:03:10

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "age", "workclass", "education_level", "educationnum", "maritalstatus", "occupation", "relationship", "race", "sex", "capitalgain", "capitalloss", "hoursperweek", "nativecountry"];
opts.VariableTypes = ["double", "double", "categorical", "categorical", "double", "categorical", "categorical", "categorical", "categorical", "categorical", "double", "double", "double", "categorical"];
opts = setvaropts(opts, [3, 4, 6, 7, 8, 9, 10, 14], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
testcensus = readtable(filename, opts);

end